#!/usr/bin/env bash

###############################################################################
##                                                                           ##
##                #########  ##           ##   #########                     ##
##                ##         ##           ##  ##       ##                    ##
##                ##         ##           ##  ##                             ##
##                #######    ##           ##  ##                             ##
##                ##          ##   ###   ##   ##                             ##
##                ##           ## ## ## ##    ##       ##                    ##
##                #########     ###   ###      #########                     ##
##                                                                           ##
##                        ewc - epub word count                              ##
##                    Written May 2026 by Sam Castle                         ##
##                                                                           ##
### VERSION ###################################################################
CURRENT_VERSION="0.2"
#
### PURPOSE ###################################################################
# determines the number of words in an epub file
#
### USAGE ##################################################################### 
# ewc <flags> <file.epub>
#
### VARIABLES #################################################################
EXIT_CODE=0 


### FUNCTIONS #################################################################

get_version() {
  echo "ewc ver. $CURRENT_VERSION"
}

check_args() {
for arg in "$@"; do 
  if [[ -f "$1" && $(file --mime-type "$1") == *"epub"* ]]; then
    FILE="$arg"
  else
    echo "Error: File not found or invalid file type." >&2
    EXIT_CODE=3
    exit $EXIT_CODE
  fi
done
}

count_words() {
  mkdir ~/.temp
  
  # quietly unzip only the .xhtml files to a temp directory
  unzip -jq "$1" "*.xhtml" -d ~/.temp
  
  # TODO for each .xhtml file, parse out the text content and count the words
  wc -w ~/.temp/* | tail -n 1 | awk '{print "Approximate word count: " $1}'
  
  # cleanup 
  rm -rf ~/.temp
}


### FLAGS ##################################################################### 
## TTY check # TODO This may be removed later to allow piping
if [[ ! -t 1 ]]; then
  echo "Error: ewc must run directly in terminal." >&2
  EXIT_CODE=2
  exit $EXIT_CODE
fi

## Version flag
if [[ "$1" == "-v" || "$1" == "--version" ]]; then
  get_version
  exit $EXIT_CODE
fi 

## Help flag
if [[ "$1" == "-h" || "$1" == "--help" || $# == 0 ]]; then
  echo "Usage: ewc <flags> <file.epub>"
  echo "Purpose: determines the number of words in an epub file"
  echo "Flags:"
  echo "  -v, --version   Show version information and exit"
  echo "  -h, --help      Show this help message and exit"
  exit $EXIT_CODE
fi  

# TODO add flag for read in from file list or stdin
# TODO add flag for multiple file support


### ARGS ######################################################################

check_args "$@"
echo "Working file: $FILE" # TODO remove this debug line


### LOGIC #####################################################################
main() {
  # FILE_NAME=$(basename "$FILE") 
  # Welcome message
  count_words "$FILE"
  exit $EXIT_CODE
}

main $@