#!/usr/bin/env bash

###############################################################################
##                                                                           ##
##                #########  ##           ##   #########                     ##
##                ##         ##           ##  ##       ##                    ##
##                ##         ##           ##  ##                             ##
##                #######    ##           ##  ##                             ##
##                ##          ##   ###   ##   ##                             ##
##                ##           ## ## ## ##    ##       ##                    ##
##                #########     ###   ###      #########                     ##
##                                                                           ##
##                        ewc - epub word count                              ##
##                    Written May 2026 by Sam Castle                         ##
##                                                                           ##
### VARIABLES #################################################################
CURRENT_VERSION="0.2"
EXIT_CODE=0 
ewc_flag_b=(false "batch")  	# flag - batch mode
ewc_flag_d=(false "debug")		# flag - debug mode (show extra debug info)
ewc_flag_f=(false "file")		# flag - read from file
ewc_flag_h=(false "help")		# flag - help
# TODO add 'quiet' flag to disable fatal except errors and final word count
ewc_flag_t=(false "tty")		# flag - TTY check
ewc_flag_v=(false "version")	# flag - version
ewc_flag_V=(false "Verbose")	# flag - verbose mode
#
### PURPOSE ###################################################################
# determines the number of words in an epub file
#
### USAGE ##################################################################### 
# ewc [-flag | --flag] [file]
#
### EXIT CODES ################################################################
# 0 - success
# 1 - invalid flag
# 2 - TTY check failed (piping not allowed)
# 3 - file not found or invalid file type
### FUNCTIONS #################################################################

	### FLAG FUNCTIONS ###
get_version() {
  echo "ewc (epub word count) version $CURRENT_VERSION"
  exit $EXIT_CODE
}

help_message() {
	printf "Purpose:  determines the number of words in an epub file.\n"
	printf "Usage:  ewc [<flags>] [file]\n"
	echo "  -b, --batch  Enable batch mode (allow multiple files)"
	# TODO debug mode exports to log file by default
	echo "  -d, --debug  Enable debug mode (exhaustive information, see 'set -x')"
	# TODO add -x flag (for XTRACE) which logs debug to console instead of file
	echo "  -f, --file  Read file names from a text file (one file per line)"
	echo "  -h, --help  Show this help message and exit"
	echo "  -t, --tty  Disable TTY check (allow piping)"
	echo "  -v, --version  Show version information and exit"
	echo "  -V, --verbose  Enable verbose output (excessive information)"
	exit $EXIT_CODE
}

verbose_output() {
  [[ ${ewc_flag_V[0]} == true ]] && echo "verbose: $*"
}

enumerate_flags() {
	local SET_FLAGS=()	# array to hold the names of flags that are set
	for opt in ${!ewc_flag_*}; do
		local -n arr_ref=$opt
    	local truthy=${arr_ref[0]}
    	local namer=${arr_ref[1]}
		[[ ${truthy} == true ]] && SET_FLAGS+=("${namer}")
	done
	verbose_output "Flags set: ${SET_FLAGS[*]}"
}

enable_tty_check() {
  if [[ ${ewc_flag_t[0]} == true ]]; then
	verbose_output && echo "verbose: TTY enabled."
  else
	echo "Error: TTY disabled." >&2
	EXIT_CODE=2
	exit $EXIT_CODE
  fi
}

file_mode() {
	echo "File mode support coming soon."
	# TODO add file mode support
}

batch_mode() {
	echo "Batch mode support coming soon."
	# TODO add multiple file support
}

	### HELPER FUNCTIONS ###
check_file() {
	# determine if the argument is a valid file and of the correct type (epub)
	#working_file=$(basename "$1")
	if [[ -f "$1" ]] && [[ "$(file --mime-type "$1")" == *"epub"* ]]; then
		echo 0
	else
		echo 3
	fi
}

parse_xml() {
	# TODO for each .xhtml file, parse out the text content and count the words
	result=$(wc -w "$1" | tail -n 1 | awk '{printf" %d", $1}')
	echo "$result"
}

get_word_counts() {
	local iterator=0
	local unzipped=()
	local words_sum=0
	local word_count=()

	# quietly unzip only the .xhtml files to a temp directory
	unzip -jq "$1" "*.xhtml" -d /tmp/ewc_temp
	verbose_output "Unzipping $1 to /tmp/ewc_temp/*"
	
	for file in /tmp/ewc_temp/*; do
		verbose_output "Unzipped file: $file"
		unzipped+=("$file")
	done

	for file in "${unzipped[@]}"; do
		word_count[iterator]=$(parse_xml "$file")
		verbose_output "Processing file: $file with ${word_count[iterator]} words"
		words_sum=$(( words_sum + word_count[iterator] ))
		iterator=$(( iterator + 1 ))
	done
	echo "Total word count: $words_sum"
	# cleanup 
	rm -rf /tmp/ewc_temp
}


### LOGIC #####################################################################

main() {

	### ARGS AND FLAGS ###

	local POSITIONAL_ARGS=()  	# array to hold non-flag arguments (file names)
	local FILE=""

	[[ $# == 0 ]] && ewc_flag_h[0]=true  # catch no arguments and show help message

	for arg in "$@"; do
		case $arg in 
			-b|--batch) 
				ewc_flag_b[0]=true 
				;;
			-d|--debug)
				ewc_flag_d[0]=true
				;;
			-f|--file) 
				ewc_flag_f[0]=true 
				;;
			-h|--help) 
				ewc_flag_h[0]=true 
				;;
			-t|--tty) 
				ewc_flag_t[0]=true 
				;;
			-v|--version) 
				ewc_flag_v[0]=true 
				;;
			-V|--Verbose) 
				ewc_flag_V[0]=true 
				;;
			-*) 
				echo "Error: Invalid flag $arg" >&2 
				EXIT_CODE=1 
				exit $EXIT_CODE 
				;;
			*)
				POSITIONAL_ARGS+=("$arg") 
				;;
		esac
	done

	[[ ${ewc_flag_V[0]} == true ]] && enumerate_flags
	
	#verbose_output "Positional arguments: ${POSITIONAL_ARGS[@]}"
	for arg in "${POSITIONAL_ARGS[@]}"; do
		verbose_output "Positional argument: $arg"
	done

	[[ ${ewc_flag_b[0]} == true ]] && batch_mode
	[[ ${ewc_flag_d[0]} == true ]] && set -x
	[[ ${ewc_flag_f[0]} == true ]] && file_mode
	[[ ${ewc_flag_h[0]} == true ]] && help_message 
	[[ ${ewc_flag_v[0]} == true ]] && get_version
	[[ ! -t 1 ]] && enable_tty_check	
	

	### MAIN LOGIC ###
	for book in "${POSITIONAL_ARGS[@]}"; do
		verbose_output "Processing file: $book"
		book_file_path=$(realpath "$book")
		verbose_output "Resolved path: $book_file_path"
		result=$(check_file "$book_file_path")
		verbose_output "File $book_file_path is valid."
		if [[ $result == 0 ]]; then
			FILE="$book_file_path"
			get_word_counts "$FILE"
		else
			echo "Error: File $book_file_path not found or invalid file type." >&2
			exit $EXIT_CODE
		fi
	done
	
	exit $EXIT_CODE
}

main "$@"